POST http://localhost:4001/api/user
Content-Type: application/json

{
    "IDENTITY": "0616196600158",
    "FIRST_NAME": "ADA",
    "MIDDLE_NAME": "ESTELA",
    "LAST_NAME": "RODRIGUEZ",
    "GENDER": "F",
    "NUM_PHONE_ONE": 90234590,
    "NUM_PHONE_REFERENCE": 89781234,
    "DAT_BIRTHDAY": "1966-02-12",
    "NAM_CITY": "Tegucigalpa",
    "ADDRESS": "Res.CAÑADA",
    "COD_ROLE": 1,
    "USER_EMAIL": "ADA@hotmail.com",
    "USER_PASSWORD": "1234"
}