POST http://localhost:4000/api/user
Content-Type: application/json
Authorization: Bearer 

{
    "IDENTITY": "080119990511",
    "FIRST_NAME": "Pedro",
    "MIDDLE_NAME": "Mauricio",
    "LAST_NAME": "Sanchez",
    "GENDER": "M",
    "NUM_PHONE_ONE": 88795900,
    "NUM_PHONE_REFERENCE": 78451236,
    "DAT_BIRTHDAY": "1998-02-12",
    "NAM_CITY": "Tegucigalpa",
    "ADDRESS": "Res.CAÑADA",
    "COD_ROLE": 1,
    "USER_EMAIL": "pedro@hotmail.com",
    "USER_PASSWORD": "Hook23"
}