POST http://localhost:4000/api/accounts-receivable
Content-Type: application/json
Authorization: Bearer 

{
    "COD_INVOICE" : 3,
    "DESCRIPTION" : "Cobro pendiente de unos lácteos",
    "TOT_BALANCE" : 100.00,
    "DAT_LIMIT" : "2022-03-14"
}