DELETE http://localhost:4001/api/purchase-invoice/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6Ikx1aXMiLCJMQVNUX05BTUUiOiJHYXJjaWEiLCJpYXQiOjE2NDYzNDkzODl9.BkFJDsJKUCWsP2bI0UAjqJc-rnFODARMFEIzBgko3vk
