PUT http://localhost:4000/api/sales-returns/
Content-Type: application/json
Authorization: Bearer 

{
    "COD_RETURN" : 5,
    "COD_PRODUCT" : 2,
    "DESCRIPTION" : "Devolución de unos lácteos",
    "CANT" : 2,
    "AMOUNT" : 110.00,
    "COD_USER" : 3,
    "DAT_RETURN" : "2022-03-16" 
}