POST http://localhost:4000/api/sale-detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlBlZHJvIiwiTEFTVF9OQU1FIjoiU2FuY2hleiIsImlhdCI6MTY0NzIyNzA0MH0.zijSBOxDf7_X5VDMu6NhfYUGhrMFUrZreDBFhAfyXzc

[
    {
        "COD_PRODUCT": 1,
        "PRICE": 20,
        "CANT_PRODUCTS": 7,
        "DISCOUNT": 0,
        "TOTAL": 140
    },
    {
        "COD_PRODUCT": 2,
        "PRICE": 25,
        "CANT_PRODUCTS": 4,
        "DISCOUNT": 0,
        "TOTAL": 100
    },
    {
        "COD_PRODUCT": 3,
        "PRICE": 25,
        "CANT_PRODUCTS": 2,
        "DISCOUNT": 0,
        "TOTAL": 50
    }
]